apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowplow-collector
  namespace: {{ .Release.Namespace }}
  {{- if .Values.collector.ingress.annotations }}
  annotations:
   {{ toYaml .Values.collector.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.url }}
      {{- if .Values.ingress.web.tls.secretName }}
      secretName: {{ .Values.collector.ingress.tls.secretName }}
      {{- end }}
      
  ingressClassName: {{ .Values.collector.ingress.className }}
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collector
                port:
                  number: 8080
