apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.iglu.database.backup.name }}
spec:
  schedule: {{ .Values.iglu.database.backup.schedule }}
  backupOwnerReference: self
  cluster:
    name: iglu-pg-db