---
apiVersion: v1
data:
  password: {{ .Values.iglu.database.password | b64enc }}
  username: {{ .Values.iglu.database.user | b64enc }}
kind: Secret
metadata:
  name: iglu-postgres-app
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  username: {{ .Values.iglu.database.masterUser | b64enc }}
  password: {{ .Values.iglu.database.masterPassword | b64enc }}
kind: Secret
metadata:
  name: iglu-postgres-master
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.iglu.database.name }}-backup-creds
data:
  ACCESS_KEY_ID: {{ .Values.iglu.database.backup.s3.keyId | b64enc }}
  ACCESS_SECRET_KEY: {{ .Values.iglu.database.backup.s3.secret | b64enc }}

