apiVersion: v1
kind: Secret
metadata:
  name: transformer-aws-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.transformer.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.transformer.aws.secretAccessKey | b64enc }}

