apiVersion: v1
kind: Secret
metadata:
  name: transformer-aws-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  access_key_id: {{ .Values.transformer.outputS3.accessKeyId | b64enc }}
  secret_access_key: {{ .Values.transformer.outputS3.secretAccessKey | b64enc }}

