apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.transformer.replicas }}
  selector:
    matchLabels:
      app: transformer
  template:
    metadata:
      labels:
        app: transformer
        checksum-config: {{ include (print $.Template.BasePath "/transformer-cm.yaml") . | sha256sum | trimSuffix "-" | trunc 63 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - transformer
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: transformer-server
          image: pragmatikai/pragmatik-transformer:1.0.1
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: transformer-config-volume
              mountPath: /pragmatik/config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
      volumes:
        - name: transformer-config-volume
          configMap:
            name: transformer-configmap
            items:
              - key: transformer-config.hocon
                path: transformer-config.hocon
              - key: iglu-config.json
                path: iglu-config.json
