kind: ConfigMap
apiVersion: v1
metadata:
  name: transformer-configmap
  namespace: {{ .Release.Namespace }}
data:
  iglu-config.json: |
    {
      "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-2",
      "data": {
        "cacheSize": 500,
        "cacheTtl": 600,
        "repositories": [{"connection":{"http":{"uri":"http://iglucentral.com"}},"name":"Iglu Central","priority":10,"vendorPrefixes":[]},{"connection":{"http":{"uri":"http://mirror01.iglucentral.com"}},"name":"Iglu Central - Mirror 01","priority":20,"vendorPrefixes":[]},{"connection":{"http":{"apikey":"{{ .Values.transformer.iglu.apiKey }}","uri":"{{ .Values.transformer.iglu.uri }}"}},"name":"Iglu Server","priority":0,"vendorPrefixes":[]}]
      }
    }
  transformer-config.hocon: |
    {
      "input": {
        "type": "kafka"
        "topicName": "{{ .Values.transformer.inputQueue.topicName }}"
        "bootstrapServers": "{{ .Values.transformer.kafka.bootstrapServiceName }}:{{ .Values.transformer.kafka.bootstrapServicePort }}"
        "consumerConf": {
          "enable_auto_commit": "false"
          "auto_offset_reset" : "latest"
          "group_id": {{ .Values.transformer.inputQueue.consumerGroupId }}
          "allow_auto_create.topics": "false"
        }
      }
      "output": {
        "type": "kafka"
        "topicName": "{{ .Values.transformer.outputQueue.topicName }}"
        "bootstrapServers": "{{ .Values.transformer.kafka.bootstrapServiceName }}:{{ .Values.transformer.kafka.bootstrapServicePort }}"
      }
      "logging": {
        "level": "INFO"
      }
    }
