apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.transformer.replicas }}
  selector:
    matchLabels:
      app: transformer
  template:
    metadata:
      labels:
        app: transformer
        checksum-config: {{ include (print $.Template.BasePath "/transformer-cm.yaml") . | sha256sum | trimSuffix "-" | trunc 63 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - transformer
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: transformer-server
          image: pragmatikai/transformer-kafka:5.6.8
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: transformer-aws-creds
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: transformer-aws-creds
                  key: secret_access_key
            - name: JAVA_OPTS
              value: -Dconfig.override_with_env_vars=true -Dorg.slf4j.simpleLogger.defaultLogLevel=info
          command:
            - "/home/snowplow/bin/snowplow-transformer-kafka"
            - "--config"
            - "/snowplow/config/config.hocon"
            - "--iglu-config"
            - "/snowplow/config/iglu-config.json"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -Dorg.slf4j.simpleLogger.defaultLogLevel=info
          volumeMounts:
            - name: transformer-config-volume
              mountPath: /snowplow/config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
      volumes:
        - name: transformer-config-volume
          configMap:
            name: transformer-configmap
            items:
              - key: config.hocon
                path: config.hocon
              - key: iglu-config.json
                path: iglu-config.json
